nombre = input("Por favor, ingresa tu nombre: ")
apellido = input("Por favor, ingresa tu apellido: ")
codigo_seccion = input("Por favor, ingresa tu código de sección: ")
sede = input("Por favor, ingresa tu SEDE: ")

print("\nInformación ingresada:")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("Código de sección:", codigo_seccion)
print("SEDE:", sede) 
